FROM python:3.11-slim

WORKDIR /app

# Install MLflow and Postgres driver
RUN pip install --no-cache-dir \
    mlflow==2.11.3 \
    psycopg2-binary==2.9.9

EXPOSE 5000
CMD ["mlflow", "server", "--help"]